name: Publish Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * 1' # Weekly on Monday at 10:00

jobs:
  php81:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: mileschou/octane
          tags: "8.1"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.1/Dockerfile

  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: mileschou/octane
          tags: "latest,8.0"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.0/Dockerfile
